language: elixir

matrix:
  include:
  - elixir: "1.10"
    otp_release: "22.0"
  - elixir: "1.10"
    otp_release: "23.0"
  - elixir: "1.11"
    otp_release: "23.0"

before_script:
  - mix deps.get
script:
  - mix check
  #- MIX_ENV=test mix do compile, test, coveralls.json, coveralls.html

cache:
  directories:
    - _build
    - deps
