language: elixir

elixir:
  - 1.10
otp_release:
  - 23.0

before_script:
  - mix deps.get
script:
  - MIX_ENV=test mix do compile, test, coveralls.json, coveralls.html
  #- MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json, coveralls.html

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
