language: elixir

elixir:
  - 1.10
#  - 1.11
otp_release:
  - 23.0

before_script:
  - mix deps.get
script:
  - MIX_ENV=test mix do compile, test, coveralls.json, coveralls.html
  #- MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json, coveralls.html

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  local_dir: doc
#  keep_history: true
#  on:
#    branch: master
