language: elixir

elixir:
  - 1.10
otp_release:
  - 22.0

before_script:
  - mix deps.get
script:
  - mix test

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
