name: check

on: [pull_request, push]

jobs:
  mix_check:
    name: mix check (Elixir ${{matrix.elixir}}, OTP ${{matrix.otp}})

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.14'
            otp: '24.3'
          - elixir: '1.14'
            otp: '25.0'
          - elixir: '1.14'
            otp: '26.0'

          - elixir: '1.15'
            otp: '24.3'
          - elixir: '1.15'
            otp: '25.0'
          - elixir: '1.15'
            otp: '26.0'

          - elixir: '1.16'
            otp: '24.3'
          - elixir: '1.16'
            otp: '25.0'
          - elixir: '1.16'
            otp: '26.0'

          - elixir: '1.17.3'
            otp: '25.0'
          - elixir: '1.17.3'
            otp: '26.0'
          - elixir: '1.17.3'
            otp: '27.0'

          - elixir: '1.18.1'
            otp: '25.0'
          - elixir: '1.18.1'
            otp: '26.0'
          - elixir: '1.18.1'
            otp: '27.0'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Cache Elixir deps
        uses: actions/cache@v3
        with:
          path: deps
          key: elixir-deps-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            elixir-deps-${{ runner.os }}-

      - name: Fetch Elixir deps
        run: mix deps.get

      - name: Cache Elixir build
        uses: actions/cache@v3
        with:
          path: _build
          key: elixir-build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('lib/**/*.ex', 'config/*.exs', 'mix.exs') }}
          restore-keys: |
            elixir-build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-
            elixir-build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-

      - name: Compile Elixir deps
        run: mix deps.compile

      - name: Run check
        run: mix check
